---
title: "Classification des données de placenta.txt"
author: "Gloria BENOIT, Dounia BENYAKHLAF, Karine DUONG, Louise LAM, Nadezhda ZHUKOVA"
date: "2023-11-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Lecture des données
```{r echo = FALSE}
# Importation des données 
my_dtf_initial <- read.table("data/placenta.txt", header = TRUE, row.names = "NOM", dec = ".") # Première ligne et colonne en indice
dim_initial <- dim(my_dtf_initial) # premières dimensions
cat("Le dtf initial est de dimensions", dim_initial, ".")
# str(my_dtf_initial)
# summary(my_dtf_initial)

ind_char <- c(1,3)
ind_ci <- which(colnames(my_dtf_initial) == "CI")
ind_ci_3 <- which(colnames(my_dtf_initial) == "CI3")
ind_ci_2 <- which(colnames(my_dtf_initial) == "CI2")
my_dtf2 <- my_dtf_initial[,-c(ind_char, ind_ci, ind_ci_3)]
my_dtf3 <- my_dtf_initial[,-c(ind_char, ind_ci, ind_ci_2)]
```

# Nettoyage des données
## Suppression des NAs
```{r echo = FALSE}
# Supprimer les NAs
nb_na_dtf2 <- sum(is.na(my_dtf2)) # calcul du nombre de NA
nb_na_dtf3 <- sum(is.na(my_dtf3)) # calcul du nombre de NA

cat("Dans my_dtf2, il y a", nb_na_dtf2,"NA.\n")
cat("Dans my_dtf3, il y a", nb_na_dtf3,"NA.")
```

## Supprimer les descripteurs à variance nulle
```{r echo = FALSE}
# Calcul des moyennes et des variances sur les descripteurs quantitatifs
moyennes2 <- apply(my_dtf2, MARGIN = 2, FUN = mean)
variances2 <- apply(my_dtf2, MARGIN = 2, FUN = var) 
hist(variances2)
moyennes3 <- apply(my_dtf3, MARGIN = 2, FUN = mean)
variances3 <- apply(my_dtf3, MARGIN = 2, FUN = var) 
hist(variances3)

ind_var_0_2 <- which(variances2 == 0)
ind_var_0_3 <- which(variances3 == 0)
dim(my_dtf2)
dim(my_dtf3)
my_dtf2 <- my_dtf2[,-ind_var_0_2]
my_dtf3 <- my_dtf3[,-ind_var_0_3]
dim(my_dtf2)
dim(my_dtf3)

cat("On a retiré", length(ind_var_0_2), "descripteurs à variance nulle.")
cat("On a retiré", length(ind_var_0_3), "descripteurs à variance nulle.")
```

## Supprimer les descripteurs trop corrélés entre eux
```{r echo = FALSE}
library(corrplot)
library(caret)
# On affiche la matrice de corrélation
matrice_corr2 <- cor(my_dtf2, method = "pearson")
matrice_corr3 <- cor(my_dtf3, method = "pearson")
corrplot(matrice_corr2, type = "lower", method = 'color')
corrplot(matrice_corr3, type = "lower", method = 'color')
print("Le plot n'est pas exploitable car il nous reste trop de variables. Supprimons les variables trop corrélées.")

# On supprime les variables dont la corrélation est > 0.85
col_suppr2 <- findCorrelation(x = matrice_corr2, cutoff = 0.90)
col_suppr3 <- findCorrelation(x = matrice_corr3, cutoff = 0.90)
my_dtf2 <- my_dtf2[,-col_suppr2]
my_dtf3 <- my_dtf3[,-col_suppr3]
dim(my_dtf2)
dim(my_dtf3)

# On raffiche la matrice de corrélation
matrice_corr2 <- cor(my_dtf2, method = "pearson")
matrice_corr3 <- cor(my_dtf3, method = "pearson")
corrplot(matrice_corr2, type = "lower", method = 'color')
corrplot(matrice_corr3, type = "lower", method = 'color')
cat("On a retiré", length(col_suppr2), "descripteurs.")
cat("On a retiré", length(col_suppr3), "descripteurs.")
```

## Distribution des VA : boxplot
```{r echo = FALSE}
# affichage des boxplot
boxplot(my_dtf2, main = "boxplot du jeu de données")
boxplot(my_dtf3, main = "boxplot du jeu de données")
print("Il y a un point abérrant.")

dim(my_dtf2)
dim(my_dtf3)
ind_ab2 <- apply(my_dtf2, 1, function(row) any(row > 1500000))
ind_ab3 <- apply(my_dtf3, 1, function(row) any(row > 1500000))
my_dtf2 <- my_dtf2[-which(ind_ab2 == TRUE),]
my_dtf3 <- my_dtf3[-which(ind_ab3 == TRUE),]
dim(my_dtf2)
dim(my_dtf3)
boxplot(my_dtf2, main = "boxplot du jeu de données")
boxplot(my_dtf3, main = "boxplot du jeu de données")

# normalisation
ind_ci_2 <- which(colnames(my_dtf2) == "CI2")
ind_ci_3 <- which(colnames(my_dtf3) == "CI3")
my_dtf2_scaled <- scale(my_dtf2[,-ind_ci_2], center = TRUE, scale = TRUE)
my_dtf3_scaled <- scale(my_dtf3[,-ind_ci_3], center = TRUE, scale = TRUE)

my_dtf2_scaled <- data.frame(my_dtf2_scaled, CI2 = my_dtf2[,ind_ci_2])
my_dtf3_scaled <- data.frame(my_dtf3_scaled, CI3 = my_dtf3[,ind_ci_3])
dim(my_dtf2_scaled)
dim(my_dtf3_scaled)

# visualisation
boxplot(my_dtf2_scaled, main = "boxplot du jeu de données normalisé")
boxplot(my_dtf3_scaled, main = "boxplot du jeu de données normalisé")
```

## ACP
```{r echo = FALSE}
library(FactoMineR)
res_PCA2 <- PCA(my_dtf2_scaled, graph = FALSE)
res_PCA3 <- PCA(my_dtf3_scaled, graph = FALSE)

# variables
plot(res_PCA2, choix = "var")
plot(res_PCA3, choix = "var")

# couples
plot(res_PCA2, habillage = ind_ci_2)
plot(res_PCA3, habillage = ind_ci_3)
```
# Téléchargement des données
```{r echo = FALSE}
write.csv(my_dtf2_scaled, file = "data/data_pred_ci2.csv")
write.csv(my_dtf3_scaled, file = "data/data_pred_ci3.csv")
```

